name: Build and deploy ASP.Net Core app to Azure Web App - cenfocinemas-dvalerio

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build WebApp
        run: dotnet build ./5_WebApp/WebApp.csproj --configuration Release

      - name: Publish WebApp
        run: dotnet publish ./5_WebApp/WebApp.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6EB4C674BE004995934B09318C750932 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F5D4FE58E7264B0796E069A7139474B3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0899A04123B455B892D9FE19A47BA4F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cenfocinemas-dvalerio'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
